#!/bin/bash
# ============================================================================
# Arboryx public frontend — deploy script
# ----------------------------------------------------------------------------
# Reads frontend/arboryx_frontend.config and:
#   1. Generates frontend/scripts/config.js (the runtime-loaded settings).
#   2. Optionally pushes the frontend/ tree to GCS or Firebase Hosting.
#
# Modes:
#   --local      (default) Just regenerate config.js in place.
#   --gcs        Generate config.js + delegate to frontend/cloudflare/deploy.sh
#                (the canonical CF+GCS deploy; this mode is a thin shim that
#                 just passes --skip-verify --skip-dns to skip the one-time
#                 setup stages and only re-sync the frontend tree).
#   --firebase   Generate config.js + firebase deploy --only hosting:SITE.
#
# Flags:
#   --dry-run    Show what would happen, don't write/upload.
#   -h | --help  Show usage.
#
# Examples:
#   bash frontend/deploy.sh                # local regenerate
#   bash frontend/deploy.sh --gcs
#   bash frontend/deploy.sh --firebase --dry-run
# ============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Colours
# ---------------------------------------------------------------------------
RED='\033[0;31m';  GREEN='\033[0;32m';  YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m';      RESET='\033[0m'
info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
err()     { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
header()  { echo -e "\n${BOLD}$*${RESET}"; }

# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------
MODE="local"
DRY_RUN=false

usage() {
  sed -n '2,22p' "$0"
  exit 0
}

for arg in "$@"; do
  case "$arg" in
    --local)    MODE="local" ;;
    --gcs)      MODE="gcs" ;;
    --firebase) MODE="firebase" ;;
    --dry-run)  DRY_RUN=true ;;
    -h|--help)  usage ;;
    *) err "Unknown argument: $arg"; usage ;;
  esac
done

# ---------------------------------------------------------------------------
# Load config
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/arboryx_frontend.config"

if [[ ! -f "$CONFIG_FILE" ]]; then
  err "Config not found: $CONFIG_FILE"
  err "Copy arboryx_frontend.config.example → arboryx_frontend.config and fill it in."
  exit 1
fi

source "$CONFIG_FILE"

# Defaults for any var the config didn't set (defensive).
: "${ARBORYX_API_URL:=}"
: "${ARBORYX_PUBLIC_API_KEY:=}"
: "${MAX_LEAVES_PER_DAY:=5}"
: "${RECENCY_DAYS:=7}"
: "${TREE_SCALE:=1.0}"
: "${LEAF_SIZE:=1.0}"
: "${GROVE_TITLE:=}"
: "${GROVE_SUBTITLE:=}"
: "${BRAND_X_HANDLE:=arboryx_ai}"
: "${BRAND_LINKEDIN_URL:=https://www.linkedin.com/company/arboryx}"
: "${BRAND_SLOGAN:=Turning Market Noise Into Your Edge}"
: "${GCS_BUCKET:=}"
: "${GCS_FRONTEND_PREFIX:=arboryx.ai/}"
: "${FIREBASE_PROJECT:=}"
: "${FIREBASE_SITE:=arboryx-ai}"

# ---------------------------------------------------------------------------
# Helper — bash bool to JS literal
# ---------------------------------------------------------------------------
js_bool() {
  case "${1:-false}" in
    true|TRUE|True|1|yes|on)  echo "true" ;;
    *)                        echo "false" ;;
  esac
}

# ---------------------------------------------------------------------------
# Generate scripts/config.js from the loaded vars
# ---------------------------------------------------------------------------
GEN_PATH="$SCRIPT_DIR/scripts/config.js"

generate_config() {
  cat > "$GEN_PATH" <<EOF
/* GENERATED by frontend/deploy.sh — do not edit by hand.
   Source of truth: frontend/arboryx_frontend.config
   Regenerate: bash frontend/deploy.sh --local
*/
window.ARBORYX_CONFIG = {
  api: {
    url:       "${ARBORYX_API_URL}",
    publicKey: "${ARBORYX_PUBLIC_API_KEY}",
  },
  grove: {
    maxLeavesPerDay: ${MAX_LEAVES_PER_DAY},
    recencyDays:     ${RECENCY_DAYS},
    treeScale:       ${TREE_SCALE},
    leafSize:        ${LEAF_SIZE},
    title:           "${GROVE_TITLE}",
    subtitle:        "${GROVE_SUBTITLE}",
  },
  sectors: [
    { name: "Robotics",           cat: 0, enabled: $(js_bool "${SECTOR_ROBOTICS_ENABLED}") },
    { name: "Crypto",             cat: 1, enabled: $(js_bool "${SECTOR_CRYPTO_ENABLED}") },
    { name: "AI Stack",           cat: 2, enabled: $(js_bool "${SECTOR_AI_STACK_ENABLED}") },
    { name: "Space & Defense",    cat: 3, enabled: $(js_bool "${SECTOR_SPACE_DEFENSE_ENABLED}") },
    { name: "Power & Energy",     cat: 4, enabled: $(js_bool "${SECTOR_POWER_ENERGY_ENABLED}") },
    { name: "Strategic Minerals", cat: 5, enabled: $(js_bool "${SECTOR_STRATEGIC_MINERALS_ENABLED}") },
  ],
  shares: {
    x:         $(js_bool "${SHARE_X_ENABLED}"),
    whatsapp:  $(js_bool "${SHARE_WHATSAPP_ENABLED}"),
    facebook:  $(js_bool "${SHARE_FACEBOOK_ENABLED}"),
    linkedin:  $(js_bool "${SHARE_LINKEDIN_ENABLED}"),
    reddit:    $(js_bool "${SHARE_REDDIT_ENABLED}"),
    telegram:  $(js_bool "${SHARE_TELEGRAM_ENABLED}"),
    email:     $(js_bool "${SHARE_EMAIL_ENABLED}"),
    instagram: $(js_bool "${SHARE_INSTAGRAM_ENABLED}"),
  },
  brand: {
    xHandle:     "${BRAND_X_HANDLE}",
    linkedinUrl: "${BRAND_LINKEDIN_URL}",
    slogan:      "${BRAND_SLOGAN}",
  },
};
EOF
}

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------
header "============================================"
header "  Arboryx Frontend — Deploy"
header "============================================"
info "Mode      : ${BOLD}${MODE}${RESET}"
info "Dry-run   : ${DRY_RUN}"
info "Source    : $SCRIPT_DIR"
info "API URL   : ${ARBORYX_API_URL:-(not set)}"
info "Public key: $(if [[ -n "$ARBORYX_PUBLIC_API_KEY" ]]; then echo 'SET'; else echo 'NOT SET'; fi)"
info "Sectors   : $(grep -cE '^SECTOR_[A-Z_]+_ENABLED=true' "$CONFIG_FILE" 2>/dev/null || echo '?') of 6 enabled"
info "Shares    : $(grep -cE '^SHARE_[A-Z_]+_ENABLED=true' "$CONFIG_FILE" 2>/dev/null || echo '?') of 8 enabled"
echo ""

# ---------------------------------------------------------------------------
# Step 1 — generate config.js
# ---------------------------------------------------------------------------
header "--- Step 1: Generate scripts/config.js ---"

if [[ "$DRY_RUN" == true ]]; then
  info "Would write: $GEN_PATH"
  info "  api.url            = ${ARBORYX_API_URL}"
  info "  api.publicKey      = $(if [[ -n "$ARBORYX_PUBLIC_API_KEY" ]]; then echo '<set>'; else echo '<empty>'; fi)"
  info "  grove.maxLeaves    = ${MAX_LEAVES_PER_DAY}"
  info "  grove.recencyDays  = ${RECENCY_DAYS}"
  info "  grove.treeScale    = ${TREE_SCALE}"
  info "  grove.title        = $(if [[ -n "$GROVE_TITLE" ]]; then echo "${GROVE_TITLE:0:50}…"; else echo '<HTML default>'; fi)"
  info "  grove.subtitle     = $(if [[ -n "$GROVE_SUBTITLE" ]]; then echo "${GROVE_SUBTITLE:0:50}…"; else echo '<HTML default>'; fi)"
  info "  brand.xHandle      = ${BRAND_X_HANDLE}"
else
  generate_config
  success "Wrote $GEN_PATH"
fi

# ---------------------------------------------------------------------------
# Step 2 — deploy (mode-dependent)
# ---------------------------------------------------------------------------
case "$MODE" in

  local)
    header "--- Step 2: Local (no upload) ---"
    info "Files in $SCRIPT_DIR are ready."
    info "Preview: ${BOLD}cd frontend && python3 -m http.server 8000${RESET}"
    info "Then open http://localhost:8000/index.html or index_v2.html"
    ;;

  gcs)
    header "--- Step 2: Delegate to frontend/cloudflare/deploy.sh ---"
    CF_DEPLOY="$SCRIPT_DIR/cloudflare/deploy.sh"
    if [[ ! -f "$CF_DEPLOY" ]]; then
      err "Canonical deploy not found: $CF_DEPLOY"
      err "The --gcs mode is a shim around it — keep them in the same repo."
      exit 1
    fi
    # Bucket name + IAM + DNS are managed by cloudflare/deploy.sh against
    # frontend/cloudflare.config (not arboryx_frontend.config). Skip the one-
    # time stages (verify, DNS) and just re-sync the frontend tree.
    CF_ARGS=(--skip-verify --skip-dns)
    $DRY_RUN && CF_ARGS+=(--dry-run)
    info "Running: bash $CF_DEPLOY ${CF_ARGS[*]}"
    bash "$CF_DEPLOY" "${CF_ARGS[@]}"
    ;;

  firebase)
    header "--- Step 2: Deploy to Firebase Hosting ---"
    if ! command -v firebase >/dev/null 2>&1; then
      err "firebase CLI not found. Install: npm i -g firebase-tools"
      err "Then: firebase login"
      exit 1
    fi
    if [[ -z "$FIREBASE_PROJECT" ]]; then
      err "FIREBASE_PROJECT not set in config"; exit 1
    fi
    if [[ ! -f "$SCRIPT_DIR/firebase.json" ]]; then
      err "firebase.json not found at $SCRIPT_DIR/firebase.json"
      err "First-time setup: cd frontend && firebase init hosting (use existing project '$FIREBASE_PROJECT', site '$FIREBASE_SITE')"
      exit 1
    fi

    info "Project : $FIREBASE_PROJECT"
    info "Site    : $FIREBASE_SITE"

    # Ensure the hosting site exists (first run creates it; idempotent after).
    if [[ "$DRY_RUN" == true ]]; then
      info "Would ensure hosting site '$FIREBASE_SITE' exists (create if missing)."
    elif firebase hosting:sites:list --project "$FIREBASE_PROJECT" 2>/dev/null | grep -qw "$FIREBASE_SITE"; then
      info "Hosting site '$FIREBASE_SITE' already exists."
    else
      info "Creating hosting site '$FIREBASE_SITE'..."
      firebase hosting:sites:create "$FIREBASE_SITE" --project "$FIREBASE_PROJECT"
      firebase target:apply hosting "$FIREBASE_SITE" "$FIREBASE_SITE" --project "$FIREBASE_PROJECT" 2>/dev/null || true
    fi

    if [[ "$DRY_RUN" == true ]]; then
      info "Would run: cd $SCRIPT_DIR && firebase deploy --only hosting:$FIREBASE_SITE --project $FIREBASE_PROJECT"
    else
      ( cd "$SCRIPT_DIR" && firebase deploy --only "hosting:$FIREBASE_SITE" --project "$FIREBASE_PROJECT" )
      success "Firebase deploy complete."
    fi
    ;;

esac

echo ""
success "Done."
