/* =========================================================================
   Arboryx public landing — interactions.

   All tunables come from window.ARBORYX_CONFIG (set by scripts/config.js,
   generated by frontend/deploy.sh from arboryx_frontend.config). Sensible
   defaults are baked in below for the case where config.js wasn't generated
   (e.g. someone opened index.html before running deploy.sh).

   Phase 3 scope:
     - Dynamic year in copyright.
     - Fetch ?action=stats with the read-only key, populate sector counts.
     - Hide trees for sectors with enabled=false.
     - Hide footer share buttons whose toggle is false.
     - Wire share / follow buttons (URLs built from window.location.href).
     - Apply tree-scale transform per CONFIG.grove.treeScale.

   Phase 4 will use CONFIG.grove.{maxLeavesPerDay, recencyDays} to render
   leaves from real entries.
   ========================================================================= */

(() => {
  'use strict';

  // ---- defaults (mirror arboryx_frontend.config) ----
  const DEFAULT_CONFIG = {
    api:    { url: '', publicKey: '' },
    grove:  { maxLeavesPerDay: 5, recencyDays: 7, treeScale: 1.0, leafSize: 1.0, title: '', subtitle: '' },
    sectors: [
      { name: 'Robotics',           cat: 0, enabled: true },
      { name: 'Crypto',             cat: 1, enabled: true },
      { name: 'AI Stack',           cat: 2, enabled: true },
      { name: 'Space & Defense',    cat: 3, enabled: true },
      { name: 'Power & Energy',     cat: 4, enabled: true },
      { name: 'Strategic Minerals', cat: 5, enabled: true },
    ],
    shares: {
      x: true, whatsapp: true, facebook: true, linkedin: true,
      reddit: true, telegram: true, email: true, instagram: true,
    },
    brand: {
      xHandle:     'arboryx_ai',
      linkedinUrl: 'https://www.linkedin.com/company/arboryx',
      slogan:      'Turning Market Noise Into Your Edge',
    },
  };

  const CONFIG = mergeConfig(DEFAULT_CONFIG, (typeof window !== 'undefined' && window.ARBORYX_CONFIG) || {});

  function mergeConfig(base, over) {
    const out = JSON.parse(JSON.stringify(base));
    if (over.api)    Object.assign(out.api, over.api);
    if (over.grove)  Object.assign(out.grove, over.grove);
    if (over.shares) Object.assign(out.shares, over.shares);
    if (over.brand)  Object.assign(out.brand, over.brand);
    if (Array.isArray(over.sectors)) out.sectors = over.sectors;
    return out;
  }

  // -- Dynamic year --
  function setDynamicYear() {
    const el = document.querySelector('[data-dynamic-year]');
    if (el) el.textContent = String(new Date().getFullYear());
  }

  // -- Slogan (config can override the HTML default) --
  function paintSlogan() {
    const el = document.querySelector('.brand-slogan');
    if (el && CONFIG.brand.slogan) el.textContent = CONFIG.brand.slogan;
  }

  // -- Grove title + inline subtitle (config can override HTML defaults) --
  function paintGroveTitle() {
    const titleEl = document.querySelector('[data-grove-title]');
    const subEl   = document.querySelector('[data-grove-subtitle]');
    if (titleEl && CONFIG.grove.title)    titleEl.textContent = CONFIG.grove.title;
    if (subEl   && CONFIG.grove.subtitle) subEl.textContent   = CONFIG.grove.subtitle;
  }

  // -- Sector visibility + tree scale --
  function applySectorToggles() {
    const enabled = new Set(CONFIG.sectors.filter((s) => s.enabled).map((s) => s.name));
    document.querySelectorAll('[data-sector]').forEach((el) => {
      const name = el.getAttribute('data-sector');
      if (!enabled.has(name)) el.style.display = 'none';
    });
  }

  function applyTreeScale() {
    const s = Number(CONFIG.grove.treeScale) || 1.0;
    if (s === 1.0) return;
    // Apply scale to each tree group around its own translate point.
    document.querySelectorAll('.tree[data-sector]').forEach((g) => {
      const t = g.getAttribute('transform') || '';
      // Append a scale; SVG composes the transform list left-to-right.
      g.setAttribute('transform', `${t} scale(${s})`);
    });
  }

  // -- Share button visibility --
  function applyShareToggles() {
    document.querySelectorAll('[data-share]').forEach((btn) => {
      const target = btn.getAttribute('data-share');
      if (!CONFIG.shares[target]) btn.style.display = 'none';
    });
  }

  // -- Stats fetch --
  // Scopes to the recency window so the count under each tree matches what
  // the leaves represent (last RECENCY_DAYS days, default 7).
  async function fetchStats() {
    const url = CONFIG.api.url;
    const key = CONFIG.api.publicKey;
    if (!url || !key) return null;
    const days = Number(CONFIG.grove.recencyDays) || 7;
    try {
      const resp = await fetch(`${url}?action=stats&days=${days}`, {
        headers: { 'X-API-Key': key },
      });
      if (!resp.ok) throw new Error(`stats ${resp.status}`);
      return await resp.json();
    } catch (err) {
      console.warn('stats fetch failed:', err);
      return null;
    }
  }

  function paintStats(stats) {
    if (!stats || !stats.categories) return;
    document.querySelectorAll('[data-sector-count]').forEach((el) => {
      const name = el.getAttribute('data-sector-count');
      if (name in stats.categories) {
        el.textContent = String(stats.categories[name]);
        el.removeAttribute('data-pending');
      }
    });
    const updated = document.querySelector('[data-last-updated]');
    if (updated && stats.date_range && stats.date_range.latest) {
      updated.textContent = `latest ${stats.date_range.latest}`;
    }
  }

  // -- Share / follow URLs (built fresh per click from current URL) --
  function shareUrlBuilders() {
    const x = CONFIG.brand.xHandle;
    const viaParam = x ? `&via=${encodeURIComponent(x)}` : '';
    return {
      x:        (url, txt) => `https://x.com/intent/tweet?text=${encodeURIComponent(txt)}&url=${encodeURIComponent(url)}${viaParam}`,
      whatsapp: (url, txt) => `https://wa.me/?text=${encodeURIComponent(`${txt} ${url}`)}`,
      facebook: (url)      => `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`,
      linkedin: (url)      => `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`,
      reddit:   (url, txt) => `https://www.reddit.com/submit?url=${encodeURIComponent(url)}&title=${encodeURIComponent(txt)}`,
      telegram: (url, txt) => `https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(txt)}`,
      email:    (url, txt) => `mailto:?subject=${encodeURIComponent(txt)}&body=${encodeURIComponent(url)}`,
      instagram: ()        => 'https://www.instagram.com',
    };
  }

  function followUrls() {
    const x = CONFIG.brand.xHandle;
    return {
      x:        x ? `https://x.com/${encodeURIComponent(x)}` : null,
      linkedin: CONFIG.brand.linkedinUrl || null,
    };
  }

  function shareText() {
    return `Arboryx — ${CONFIG.brand.slogan.toLowerCase()}.`;
  }

  function wireShareButtons() {
    const builders = shareUrlBuilders();
    document.querySelectorAll('[data-share]').forEach((btn) => {
      btn.addEventListener('click', () => {
        const target = btn.dataset.share;
        const builder = builders[target];
        if (!builder) return;
        const url = builder(window.location.href, shareText());
        window.open(url, '_blank', 'noopener,noreferrer');
      });
    });
    const followsMap = followUrls();
    document.querySelectorAll('[data-follow]').forEach((btn) => {
      btn.addEventListener('click', () => {
        const target = btn.dataset.follow;
        const u = followsMap[target];
        if (u) window.open(u, '_blank', 'noopener,noreferrer');
      });
    });
  }

  // -- Boot --
  document.addEventListener('DOMContentLoaded', async () => {
    setDynamicYear();
    paintSlogan();
    paintGroveTitle();
    applySectorToggles();
    applyTreeScale();
    applyShareToggles();
    wireShareButtons();
    const stats = await fetchStats();
    paintStats(stats);
  });

  // Phase-4 hook + test surface.
  window.__arboryx = { CONFIG, fetchStats, paintStats };
})();
